19362336 | feat: added in php-8.2-bullseye container (INTERIM)
10up/wordpress-ci-container pull request #17
Opened 2023-10-06 11:52 UTC by syedahmedhaidershah

### Description of the Change
Added in support for PHP 8.2 containers in CI and fixed relative packages during container build.

#### My WSL Distro
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

#### _**Changes**_
- Added `php:8.2-bullseye` to `base_containers` for build job, `build_push_to_dockerhub`.
- Added in a step for configuring php 8.2 settings:
```yaml
  - name: Set PHP 8.2 settings
        if: ${{ matrix.base_container == 'php:8.2-bullseye' }}
        run: |
          echo "BUILD_TAGS=10up/wordpress-ci:php-8.2" >> $GITHUB_ENV
          echo "COMPOSER_VERSION=2" >> $GITHUB_ENV
```
- Updated `install-node.sh` due to the following issue, fixed in a more specific LTS version of 16 (v16.20.2 - gallium):
![image](https://github.com/10up/wordpress-ci-container/assets/43408958/11762026-4efd-43e5-8f07-0f7f1b2d630c)

- Cypress version added since latest supports `v18.x and above`. Setting Cypress version to _**~13.1**_ according to [cypress changelog](https://docs.cypress.io/guides/references/changelog#13-1-0) for supporting node `v16.x` releases, open for patch updates.
_**REF**_:
![image](https://github.com/10up/wordpress-ci-container/assets/43408958/0d624f58-783d-44cb-8976-8eee090782d7)

#### _**Commands used for tests:**_
1. Building image:
```bash
docker build --build-arg PHP_IMG=php:8.2-bullseye .
```
We have a successful build:
![image](https://github.com/10up/wordpress-ci-container/assets/43408958/1339a57c-8f45-4d19-92cc-9ff8f39da5da)
2. Creating a container:
```bash
# Image was created without name, so I passed the image id manually
docker run -it --name=wp-ci-container-test 42e301a7fcce2a1b9b50c0227f0fc4aaae7ce107051151d428b5d1a53f542b58
```
❗ The container exists without any issues.
![image](https://github.com/10up/wordpress-ci-container/assets/43408958/7dd67c4b-6a4e-48b2-9c0d-b493c6a401ac)

#### _**Notes:**_
1. Internal projects such as _**Ci-Library**_ and _**Ansible Playbooks**_ would need to be updated to utilize the updated PHP image.

#### _**Issue Reference**_
https://tenup.teamwork.com/app/tasks/19362336
### How to test the Change

### Changelog Entry
> Added - `php-8.2-bullseye` support to build containers for php 8.2
> Fixed - `node-version` installed via nvm from `16` to `v16.20.2`
> Fixed - `npm:cypress` to version `~13.1` to match with gallium (node `v16.x-lts`) 

### Credits
Props @syedahmedhaidershah @pablojmarti

### Checklist:
- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-10-06 11:58 UTC, pablojmarti commented on build/install-node.sh
> +NODE_VERSION="v16.20.2"
@syedahmedhaidershah for the same reasons we discussed using the `~13.1` for cypress we want to ensure we are using the latest version of node. Can you do further testing to understand why setting it to 16 did not work? I would recommend running the base image directly and then manually running these commands. It's possible that NVM needs to be updated as well.

2023-10-06 11:58 UTC, pablojmarti requested changes
@syedahmedhaidershah for the same reasons we discussed using the `~13.1` for cypress we want to ensure we are using the latest version of node. Can you do further testing to understand why setting it to 16 did not work? I would recommend running the base image directly and then manually running these commands. It's possible that NVM needs to be updated as well.

2023-10-06 14:32 UTC, syedahmedhaidershah commented
Hey @pablojmarti 
- Won't you prefer that we do not upgrade node to the latest, if required, I pretty much upgrade it to just LTS? For now, or we can atleast align with the web team on which version of Node they are using?
- I can look into the NVM issue why the tag `16` did not work.

2023-10-10 11:23 UTC, syedahmedhaidershah commented
- Nvm 16 version was fixed, probably reaching deps endpoint issue, resolved via company VPN for building for local. It targets LTS automatically for a specific release version. Had to adjust some deps _**(lightouse, cypress)**_ with latest releases failing for specific and `>=` depedency.

2023-10-16 14:47 UTC, merged